name: Primary Workflow

on: 
  push:
    branches: 
    - main
  
  # Executar de forma manual
  workflow_dispatch: 

jobs:
  primary-job:
    name: "Primary Job"
    runs-on: ubuntu-latest


    steps:
      - name: "Primary action"
        run: echo "Hello World !!"

      - name: "Second action"
        run: |
          echo: "Primary workflow OK"
          echo: "Congratulations"


  