name: Install Java 5 on GitHub Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://download.oracle.com/java/1.5.0_22/jdk-1_5_0_22-linux-i586.bin
          chmod +x jdk-1_5_0_22-linux-i586.bin
          echo "yes" | ./jdk-1_5_0_22-linux-i586.bin
          sudo mv jdk1.5.0_22 /usr/lib/jvm/

      - name: Set JAVA_HOME to Java 5
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/jdk1.5.0_22" >> $GITHUB_ENV
          echo "/usr/lib/jvm/jdk1.5.0_22/bin" >> $GITHUB_PATH

      - name: Verify Java version
        run: java -version

